language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - redis-server
# command to install redisco with dependencies
install:
  - pip install .
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then nosetests --with-doctest; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then nosetests --with-doctest; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then nosetests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then nosetests; fi
